source "https://rubygems.org"

gem "foreman"
gem "rake"
gem "guard"
gem "guard-shell"
gem "terminal-notifier"
gem "terminal-notifier-guard"
gem "sinatra"
gem "sinatra-contrib"
gem "pry"
gem "test-unit"
gem "colorize"
gem "unindent"
gem "hashie"
